import { NextRequest, NextResponse } from 'next/server';
import { query, queryOne } from '@/lib/db';
import bcrypt from 'bcryptjs';

// POST /api/users — create user with role
export async function POST(req: NextRequest) {
    try {
        const body = await req.json();
        const {
            email,
            password,
            full_name,
            role_name,
            school_id,
            phone,
            address,
            dob,
            class_id,
            subject_name,
        } = body;

        // Special handling for Student (no auth account)
        if (role_name === 'Student') {
            const student = await queryOne(
                `INSERT INTO students_data (school_id, class_id, full_name, email, phone, current_address, dob)
                 VALUES ($1, $2, $3, $4, $5, $6, $7)
                 RETURNING id`,
                [school_id, class_id || null, full_name, email, phone || null, address || null, dob || null]
            );
            return NextResponse.json({ success: true, user_id: (student as any).id });
        }

        // Look up role
        const roleRow = await queryOne<{ id: string }>(
            `SELECT id FROM roles WHERE role_name = $1`,
            [role_name]
        );
        if (!roleRow) return NextResponse.json({ success: false, error: `Invalid role: ${role_name}` }, { status: 400 });

        const role_id = roleRow.id;

        // Hash password
        const tempPassword = password || 'tempPassword123';
        const password_hash = await bcrypt.hash(tempPassword, 12);

        // Check if profile already exists
        const existing = await queryOne<{ id: string }>(
            `SELECT id FROM profiles WHERE email = $1`,
            [email]
        );

        let userId: string;
        if (existing) {
            userId = existing.id;
            // Update existing profile
            await queryOne(
                `UPDATE profiles SET
                    role_id = $1, school_id = $2, full_name = $3,
                    phone = $4, current_address = $5, dob = $6,
                    password_hash = $7, is_deleted = false
                 WHERE id = $8`,
                [role_id, school_id || null, full_name, phone || null, address || null, dob || null, password_hash, userId]
            );
        } else {
            // Create new profile (with UUID generated by DB)
            const profile = await queryOne<{ id: string }>(
                `INSERT INTO profiles (role_id, school_id, full_name, email, phone, current_address, dob, password_hash)
                 VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
                 RETURNING id`,
                [role_id, school_id || null, full_name, email, phone || null, address || null, dob || null, password_hash]
            );
            if (!profile) throw new Error('Profile creation failed');
            userId = profile.id;
        }

        // Create teachers_data if teacher
        if (role_name === 'Teacher') {
            const existingTd = await queryOne(`SELECT id FROM teachers_data WHERE id = $1`, [userId]);
            if (!existingTd) {
                await queryOne(
                    `INSERT INTO teachers_data (id, class_ids, subject_specialization)
                     VALUES ($1, $2, $3)`,
                    [userId, [], subject_name || null]
                );
            } else {
                await queryOne(
                    `UPDATE teachers_data SET subject_specialization = $1 WHERE id = $2`,
                    [subject_name || null, userId]
                );
            }
        }

        return NextResponse.json({ success: true, user_id: userId });
    } catch (error: any) {
        console.error('Create User Error:', error);
        return NextResponse.json({ success: false, error: error.message }, { status: 500 });
    }
}
